const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
let esbuild;
try{esbuild=require('esbuild')}catch(error){
  console.error('Missing esbuild. Install the pinned Phase 0.5 tool with: npm install --no-save --package-lock=false esbuild@0.28.2');
  throw error;
}

const repoRoot=path.resolve(__dirname,'..');
const sourceRoot=path.resolve(process.env.MIAAD_SOURCE_ASSETS||path.join(repoRoot,'app/src/main/assets'));
const outRoot=path.resolve(process.env.MIAAD_COMPAT_OUT||path.join(repoRoot,'app/build/generated/compatAssets'));
const auditRoot=path.resolve(process.env.MIAAD_AUDIT_DIR||path.join(repoRoot,'audit'));
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'compat-manifest.json'),'utf8'));
const hash=value=>crypto.createHash('sha256').update(value).digest('hex');

if(sourceRoot===outRoot||outRoot.startsWith(sourceRoot+path.sep))throw new Error('Compatibility output must not live inside source assets.');
fs.rmSync(outRoot,{recursive:true,force:true});
fs.mkdirSync(outRoot,{recursive:true});
fs.cpSync(sourceRoot,outRoot,{recursive:true});

const files=[];
for(const file of manifest.shippingScripts){
  const sourcePath=path.join(sourceRoot,file);
  const outputPath=path.join(outRoot,file);
  if(!fs.existsSync(sourcePath))throw new Error(`Missing shipping source: ${file}`);
  const source=fs.readFileSync(sourcePath,'utf8');
  const result=esbuild.transformSync(source,{
    loader:'js',
    target:manifest.runtime.syntaxTarget,
    platform:'browser',
    minify:false,
    treeShaking:false,
    legalComments:'inline',
    charset:'utf8',
    sourcemap:false,
    sourcefile:file
  });
  const generated=`/* GENERATED FOR ${manifest.runtime.syntaxTarget.toUpperCase()} BY ${manifest.tooling.transformer}. EDIT SOURCE, NOT THIS FILE. */\n${result.code}`;
  fs.writeFileSync(outputPath,generated,'utf8');
  files.push({file,sourceBytes:Buffer.byteLength(source),generatedBytes:Buffer.byteLength(generated),sourceSha256:hash(source),generatedSha256:hash(generated)});
}

const index=fs.readFileSync(path.join(outRoot,'index.html'),'utf8');
const loaded=[...index.matchAll(/<script\b[^>]*\bsrc=["']([^"']+\.js)["'][^>]*><\/script>/g)].map(match=>match[1]);
if(JSON.stringify(loaded)!==JSON.stringify(manifest.shippingScripts)){
  throw new Error(`Shipping script order does not match compatibility manifest. index=${JSON.stringify(loaded)} manifest=${JSON.stringify(manifest.shippingScripts)}`);
}

fs.mkdirSync(auditRoot,{recursive:true});
const report={contract:manifest.runtime,tooling:manifest.tooling,sourceRoot:path.relative(repoRoot,sourceRoot),generatedRoot:path.relative(repoRoot,outRoot),sourceBytes:files.reduce((n,x)=>n+x.sourceBytes,0),generatedBytes:files.reduce((n,x)=>n+x.generatedBytes,0),files};
fs.writeFileSync(path.join(auditRoot,'compat-generation.json'),JSON.stringify(report,null,2)+'\n');
console.log(`Compatibility generation PASS: ${files.length} classic scripts -> ${manifest.runtime.syntaxTarget}; ${report.sourceBytes} source bytes -> ${report.generatedBytes} generated bytes; no bundle/minify/tree-shaking.`);
