const assert=require('node:assert/strict');
const path=require('node:path');
const assetRoot=path.resolve(process.env.MIAAD_ASSET_ROOT||path.join(__dirname,'../app/src/main/assets'));
const {createMiaadDomain}=require(path.join(assetRoot,'app-domain.js'));
let now=new Date('2026-10-08T20:00:00');
const make=()=>createMiaadDomain({}, {},()=>now);
const d=make(),s=d.saveStudent({name:'Acceptance student',startDate:'2026-09-01',custom:false,settings:{}}),sid=s.id;
const c=d.cycle(sid);d.setTarget(sid,12);
const add=(date,status='entered',time='17:00',duration=30)=>d.record({studentId:sid,date,time,duration,status,note:'Teacher note'});
const records=[];for(let i=1;i<=11;i++)records.push(add(`2026-09-${String(i).padStart(2,'0')}`));
assert.throws(()=>add('2026-09-01'));assert.equal(d.cycleStats(c).counted,11);const twelfth=add('2026-09-12');assert.equal(d.cycleStats(c).counted,12);
d.notifications();d.notifications();assert.equal(Object.values(d.data.notifications).filter(n=>n.type==='cycle'&&n.active).length,1);
d.record({...twelfth,status:'student_cancelled'});assert.equal(d.cycleStats(c).counted,11);d.notifications();assert.equal(d.data.notifications['cycle:'+c.id].active,false);
d.record({...twelfth,status:'entered'});d.notifications();assert.equal(Object.values(d.data.notifications).filter(n=>n.type==='cycle').length,1);
const p=d.editPeriod(d.period(sid),'2026-09-08','2026-10-07','custom');add('2026-10-07');assert.equal(d.report(p).rows.some(r=>r.date==='2026-09-07'),false);assert.equal(d.report(p).rows.some(r=>r.date==='2026-10-07'),true);assert.equal(d.createPeriod(sid,p.start,p.end).id,p.id);assert.throws(()=>d.createPeriod(sid,'2026-10-01','2026-10-20'));
d.archive(p);const original=JSON.stringify(d.report(p));d.nextPeriod(p);assert.equal(JSON.stringify(d.report(p)),original);assert(d.data.periods[p.id]);
const rule=d.copy(d.data.settings);rule.rules.absent=false;d.saveSettings(rule);const a=add('2026-10-01','absent');assert.equal(d.counts(a),false);d.record({...a,countOverride:true});assert.equal(d.counts(d.data.records[a.id]),true);
const reloaded=createMiaadDomain(JSON.parse(JSON.stringify(d.data)),{},()=>now);assert.deepEqual(reloaded.report(reloaded.data.periods[p.id]),d.report(p));
const legacy={lessons:[{id:'weekly',name:'Existing student',day:2,start:'17:00',duration:30,repeat:'weekly'}],sessionState:{'2026-09-08__weekly':'entered'},sessionNotes:{'2026-09-08__weekly':'Preserve this'},idrisPhase:0};
now=new Date('2026-09-15T10:00:00');const migrated=createMiaadDomain({},legacy,()=>now),ms=Object.values(migrated.data.students)[0];migrated.saveSchedule({...legacy.lessons[0],studentId:ms.id,start:'18:00'});assert.equal(migrated.occurrences('2026-09-08')[0].time,'17:00');assert.equal(migrated.occurrences('2026-09-22')[0].time,'18:00');assert.equal(migrated.occurrences('2026-09-08')[0].note,'Preserve this');
const again=createMiaadDomain(migrated.data,legacy,()=>now);assert.equal(Object.keys(again.data.records).length,1);migrated.deleteSchedule('weekly');assert.equal(migrated.occurrences('2026-09-22').length,0);assert.equal(migrated.occurrences('2026-09-08')[0].time,'17:00');
const av=make(),as=av.saveStudent({name:'Availability student',startDate:'2026-09-01'}),config=av.copy(av.data.settings);config.working[2]=[['17:30','19:00']];config.minSlot=30;av.saveSettings(config);
const lesson=av.record({studentId:as.id,date:'2026-09-15',time:'18:00',duration:30,status:'pending'});assert.deepEqual(av.availability('2026-09-15').map(x=>[x.start,x.end]),[[1050,1080],[1110,1140]]);av.removeRecord(lesson);assert.deepEqual(av.availability('2026-09-15').map(x=>[x.start,x.end]),[[1050,1140]]);
av.record({...lesson,deleted:false});now=new Date('2026-09-15T19:00:00');av.notifications();assert.equal(av.data.records[lesson.id].status,'pending');assert.equal(av.stats([lesson]).attended,0);assert(av.data.notifications['pending:'+lesson.id].active);av.notifications();assert.equal(Object.values(av.data.notifications).filter(n=>n.type==='pending').length,1);
const cfg=av.copy(av.data.settings);cfg.working[2]=[['16:00','23:30']];cfg.blocked=[{day:2,start:'19:00',end:'19:30'},{date:'2026-09-15',start:'21:00',end:'22:00'}];av.removeRecord(lesson);av.record({...lesson,id:'fixed',time:'17:00',deleted:false});av.saveSettings(cfg);assert.deepEqual(av.availability('2026-09-15').map(x=>[x.start,x.end]),[[960,1020],[1050,1140],[1170,1260],[1320,1410]]);
cfg.buffer=15;av.saveSettings(cfg);assert.equal(av.availability('2026-09-15')[0].end,1005);
cfg.working[2]=[['22:00','02:00']];cfg.working[3]=[];cfg.blocked=[];cfg.buffer=0;av.saveSettings(cfg);assert.deepEqual(av.availability('2026-09-16').map(x=>[x.start,x.end]),[[0,120]]);
const hist=make(),hs=hist.saveStudent({name:'Historical student',startDate:'2026-09-01'});for(let i=1;i<=10;i++)hist.record({studentId:hs.id,date:`2026-09-${String(i).padStart(2,'0')}`,time:'09:00',duration:30,status:'entered'});assert.equal(hist.cycleStats(hist.cycle(hs.id)).counted,10);assert.equal(hist.report(hist.period(hs.id)).stats.minutes,300);
assert.throws(()=>hist.record({studentId:hs.id,date:'2026-11-01',time:'09:00',duration:30,status:'entered'}));assert.throws(()=>hist.setTarget(hs.id,0));
assert.deepEqual(hist.periodBounds('2026-01-31','monthly',31),{start:'2026-01-31',end:'2026-02-27'});
console.log('PASS: cycles, reversal, deduplication, inclusive periods, archive, reload/migration, history, schedule revisions/deletion, split, buffers, blocked time, overnight working, pending, historical import and validation.');

const rolling=make(),rs=rolling.saveStudent({name:'Rolling period',startDate:'2026-09-08'}),rp=rolling.createPeriod(rs.id,'2026-09-08','2026-10-07','monthly');assert.equal(rolling.nextPeriod(rp).end,'2026-11-07');
const future=make(),fsu=future.saveStudent({name:'Future enrolment',startDate:'2028-01-01'});assert.equal(future.cycleStats(future.cycle(fsu.id)).counted,0);future.notifications();

const cycles=make(),cs=cycles.saveStudent({name:'Cycle integrity',startDate:'2026-09-01'}),cr=cycles.record({studentId:cs.id,date:'2026-09-01',time:'09:00',duration:30,status:'entered'}),oldCycle=cycles.cycle(cs.id),newCycle=cycles.newCycle(cs.id);newCycle.start='2026-09-01';assert.equal(cycles.cycleStats(newCycle).counted,0);cycles.record({studentId:cs.id,date:'2026-09-02',time:'09:00',duration:30,status:'entered'});assert.equal(cycles.cycleStats(oldCycle).counted,2);assert.equal(cycles.cycleStats(newCycle).counted,0);cycles.removeRecord(cr);assert.equal(cycles.cycleStats(oldCycle).attended,1);
