const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL||'chrome'});const out=path.join(__dirname,'../audit/browser');fs.mkdirSync(out,{recursive:true});
const results=[];
for(const [name,width,height] of [['phone',390,844],['desktop',1440,1000]]){
 const context=await browser.newContext({viewport:{width,height},locale:'ar-EG',reducedMotion:'reduce'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.goto('file:///'+path.join(__dirname,'../app/src/main/assets/index.html').replaceAll('\\','/'));await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(out,name+'-today.png'),fullPage:true});
 assert.deepEqual(errors,[]);
 await page.locator('[data-view="students"]').click();await page.locator('#createStudent').click();await page.locator('#studentForm [name="name"]').fill('طالب اختبار');await page.locator('#studentForm [name="startDate"]').fill('2026-09-01');await page.locator('#studentForm button.save-btn').click();await page.locator('#addPast').waitFor();
 await page.locator('#addPast').click();await page.locator('.record-form [name="date"]').fill('2026-09-02');await page.locator('.record-form [name="time"]').fill('17:00');await page.locator('.record-form [name="status"]').selectOption('entered');await page.locator('.record-form [name="note"]').fill('ملاحظة تعليمية كاملة — Improvement in reading accuracy.');await page.locator('.record-form button[type="submit"], .record-form button:not([type])').click();
 assert.match(await page.locator('.cycle-progress').innerText(),/1 \/ 12/);await page.screenshot({path:path.join(out,name+'-profile.png'),fullPage:true});
 const sid=await page.evaluate(()=>selectedStudent);await page.reload();await page.locator('[data-view="students"]').click();await page.locator(`[data-student="${sid}"]`).click();assert.match(await page.locator('.cycle-progress').innerText(),/1 \/ 12/);
 await page.locator('#currentReport').click();await page.locator('#reportLanguage').selectOption('ar');await page.screenshot({path:path.join(out,name+'-report-ar.png'),fullPage:true});const ar=await page.evaluate(()=>JSON.stringify(reportData().stats)),records=await page.evaluate(()=>JSON.stringify(domain.data.records));await page.locator('#reportLanguage').selectOption('en');assert.equal(await page.locator('.professional-report').getAttribute('dir'),'ltr');assert.equal(await page.evaluate(()=>JSON.stringify(reportData().stats)),ar);assert.equal(await page.evaluate(()=>JSON.stringify(domain.data.records)),records);await page.screenshot({path:path.join(out,name+'-report-en.png'),fullPage:true});
 await page.emulateMedia({media:'print'});await page.pdf({path:path.join(out,name+'-report-en.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});
 await page.locator('[data-view="settings"]').click();await page.screenshot({path:path.join(out,name+'-settings.png'),fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false);assert.deepEqual(errors,[]);results.push({name,errors,overflow,languageInvariant:true,reload:true,pastEntry:true});await context.close();
}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2));await browser.close();console.log(JSON.stringify(results));})().catch(e=>{console.error(e);process.exit(1)});
